// packages/web/src/app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext"; // ⬅️ AuthProvider import
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <AuthProvider>
          <Header /> {/* ⬅️ Header를 여기에 추가 */}
          <main>{children}</main> {/* ⬅️ children을 main 태그로 감싸주면 좋습니다. */}
        </AuthProvider>
      </body>
    </html>
  );
}